import React,{useEffect,useRef,useState} from 'react';
import ReactDOM from 'react-dom/client';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';
import {io} from 'socket.io-client';

function App(){
 const mapEl=useRef(null), map=useRef(null), marker=useRef(null), socket=useRef(null), others=useRef(new Map());
 const [pos,setPos]=useState([42.3601,-71.0589]),[speed,setSpeed]=useState(0),[heading,setHeading]=useState(0),[room,setRoom]=useState(''),[name,setName]=useState('Driver'),[dest,setDest]=useState(''),[status,setStatus]=useState('Waiting for GPS'),[tracking,setTracking]=useState(false),[stats,setStats]=useState({start:0,top:0,avg:0,count:0,dist:0}), prev=useRef(null), line=useRef(null), route=useRef(null);
 const icon=(n,m,h,other=false)=>L.divIcon({className:'',iconSize:[70,62],iconAnchor:[35,48],html:`<div class="car ${other?'other':''}"><div class="tag">${n} · ${Math.round(m)} MPH</div><img src="./gti.svg" style="transform:rotate(${h||0}deg)"></div>`});
 useEffect(()=>{map.current=L.map(mapEl.current,{zoomControl:false}).setView(pos,15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map.current);L.control.zoom({position:'bottomright'}).addTo(map.current);marker.current=L.marker(pos,{icon:icon('YOU',0,0)}).addTo(map.current);},[]);
 useEffect(()=>{if(!navigator.geolocation){setStatus('GPS unavailable');return;}const id=navigator.geolocation.watchPosition(p=>{const n=[p.coords.latitude,p.coords.longitude],mph=Math.max(0,(p.coords.speed||0)*2.236936),hd=p.coords.heading||heading;setPos(n);setSpeed(mph);setHeading(hd);setStatus(`GPS ±${Math.round(p.coords.accuracy)}m`);marker.current?.setLatLng(n).setIcon(icon('YOU',mph,hd));if(tracking){if(prev.current){const d=L.latLng(prev.current).distanceTo(L.latLng(n))/1609.344;setStats(s=>({...s,dist:s.dist+d,top:Math.max(s.top,mph),avg:(s.avg*s.count+mph)/(s.count+1),count:s.count+1}));}prev.current=n;if(!line.current)line.current=L.polyline([],{weight:5}).addTo(map.current);line.current.addLatLng(n);}if(socket.current&&room)socket.current.emit('telemetry',{room,name,lat:n[0],lng:n[1],speed:mph,heading:hd});},e=>setStatus(e.message),{enableHighAccuracy:true,maximumAge:1000});return()=>navigator.geolocation.clearWatch(id)},[tracking,room,name]);
 async function go(e){e.preventDefault();try{setStatus('Routing…');const g=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(dest)}`).then(r=>r.json());if(!g[0])throw Error('Destination not found');const d=[+g[0].lat,+g[0].lon],r=await fetch(`https://router.project-osrm.org/route/v1/driving/${pos[1]},${pos[0]};${d[1]},${d[0]}?overview=full&geometries=geojson`).then(r=>r.json());if(!r.routes?.[0])throw Error('No route');route.current?.remove();route.current=L.geoJSON(r.routes[0].geometry,{style:{weight:7}}).addTo(map.current);map.current.fitBounds(route.current.getBounds(),{padding:[30,30]});setStatus(`${(r.routes[0].distance/1609.344).toFixed(1)} mi · ${Math.round(r.routes[0].duration/60)} min`)}catch(err){setStatus(err.message)}}
 function join(code=room){code=code.trim().toUpperCase();if(!code)return;setRoom(code);socket.current?.disconnect();socket.current=io(`http://${location.hostname}:3001`);socket.current.on('connect',()=>socket.current.emit('join-room',{room:code,name}));socket.current.on('room-state',drivers=>{const seen=new Set();drivers.forEach(d=>{if(d.socketId===socket.current.id||!d.lat)return;seen.add(d.socketId);let m=others.current.get(d.socketId);if(!m){m=L.marker([d.lat,d.lng],{icon:icon(d.name,d.speed,d.heading,true)}).addTo(map.current);others.current.set(d.socketId,m)}else m.setLatLng([d.lat,d.lng]).setIcon(icon(d.name,d.speed,d.heading,true));});for(const [id,m] of others.current)if(!seen.has(id)){m.remove();others.current.delete(id)}})}
 function create(){join(Math.random().toString(36).slice(2,8).toUpperCase())}
 function drive(){if(!tracking){setStats({start:Date.now(),top:0,avg:0,count:0,dist:0});prev.current=null;line.current?.remove();line.current=null;setTracking(true)}else{setTracking(false);localStorage.setItem('lastDrive',JSON.stringify({...stats,ended:Date.now()}));}}
 return <div className="app"><div ref={mapEl} className="map"/><div className="top"><b>GTI NAV</b><form onSubmit={go}><input value={dest} onChange={e=>setDest(e.target.value)} placeholder="Where to?"/><button>GO</button></form></div><div className="status">{status}</div><button className="loc" onClick={()=>map.current.flyTo(pos,17)}>◎</button><div className="speed"><strong>{Math.round(speed)}</strong><span>MPH</span></div><div className="panel"><div className="numbers"><span>{stats.dist.toFixed(2)} MI</span><span>{Math.round(stats.avg)} AVG</span><span>{Math.round(stats.top)} TOP</span></div><div className="buttons"><button onClick={drive}>{tracking?'END DRIVE':'START DRIVE'}</button><button onClick={create}>CREATE CONVOY</button></div><div className="convoy"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Code"/><button onClick={()=>join()}>JOIN</button></div></div></div>
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
